#!/usr/bin/env bash
export API_INSTALL_DIR="/opt/dokku-api"
export API_GOPATH="$API_INSTALL_DIR"
export API_SERVER_REPO="github.com/nikelmwann/dokku-api-server"

export API_CONTAINER_NAME="dokku-api-sock"

export API_SOCKET_DIR="/tmp/dokku-api"

export API_SOCKET="$API_SOCKET_DIR/api/dokku-api"
export API_SOCKET_URL="unix://$API_SOCKET"
