#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$(dirname "$0")/functions"

APP="$1"
verify_app_name "$APP"

api_cache fetch app "$APP"
